export { ActionPlanPage } from "@/components/platform/modules/action-plan-page";
export { AiSystemsPage } from "@/components/platform/modules/ai-systems-page";
export { AssistantPage } from "@/components/platform/modules/assistant-page";
export { CloudInventoryPage } from "@/components/platform/modules/cloud-inventory-page";
export { ControlsPage } from "@/components/platform/modules/controls-page";
export { EvidencePage } from "@/components/platform/modules/evidence-page";
export { IncidentsPage } from "@/components/platform/modules/incidents-page";
export { MaturityPage } from "@/components/platform/modules/maturity-page";
export { OnboardingPage } from "@/components/platform/modules/onboarding-page";
export { PoliciesPage } from "@/components/platform/modules/policies-page";
export { ReadinessPage } from "@/components/platform/modules/readiness-page";
export { ReportsPage } from "@/components/platform/modules/reports-page";
export { RisksPage } from "@/components/platform/modules/risks-page";
export { VendorsPage } from "@/components/platform/modules/vendors-page";
export { AdminPage, FrameworkPage, ResourcesPage, SettingsPage } from "@/components/platform/modules/static-pages";
